-- ============================================================================
-- Intentionally empty.
--
-- This migration used to insert the TVÅ Development tenant
-- (tvadevelopment.se). That is seed data, not schema, so it moved to
-- supabase/seed.sql, which runs on `npx supabase db reset`.
--
-- The file is kept (rather than deleted) so databases that already applied
-- this version keep a valid supabase_migrations.schema_migrations row.
-- ============================================================================
